### PR TITLE
Update Customer Record

### PR DESCRIPTION
**Pull request by zmonteca**
This allows execution of updating customer records via the
UpdateCustomer method and also via the purchase method using the Sale
method.

### CODE REVIEW

**Comment by iddqdidkfa** [comment]
I can't accpet this PR while it breaks Travis build, but looks like after previous PR we have two places with same mock files. You can add your mock file to second place to pass Travis build and then I will do somthing with this duplication. Or you can fix this duplication and remove duplicate mock files to pass Travis build.

**Comment by zmonteca** [comment]
OK. Working on that now. Thanks.

**Comment by zmonteca** [comment]
Should be all good. That was quite a pain, but I think we're all good now and have one single mock directory to work from. Win. Win.

**Comment by iddqdidkfa** [comment]
One more small improvement: can you please calculate test credit card expiration year from current year in `tests/Messages/CreditCard/UpdateCardRequestTest.php`. Just don`t want to update tests in 2020. Thanks for your contribution!

**Comment by zmonteca** [comment]
Sure, i'll update that now.

You know what, that "empty" files in `tests/Messages/CreditCard/Mock/empty` and `/tests/Messages/Check/Mock/empty` thing was the only way I could get the pathing I did to work properly. It was driving me made and that was the only work around I could come up with.

`$httpResponse = $this->getMockHttpResponse('../../../Mock/CreditCard/CaptureResponseSuccess.txt');`

I think what the deal was is if you are moving around using `../`, if the dir doesn't exists, it bork in the process.

**Comment by iddqdidkfa** [comment]
ok I'll try to do something with it later, and will update expiration year for `(string)((int)date('Y) + 2)`

**Comment by zmonteca** [comment]
Ok. Let me know what solution you come up with for that. It was wrecking my brain.

As for the date solutions, much smarter. Sorry, wasn't thinking there.

**Comment by zmonteca** [comment]
Are you going to create a new tag for this release, say v1.2 so this update propagates to users?

**Comment by iddqdidkfa** [comment]
@zmonteca yeah, sorry, was in a long vocation and forgot

**Comment by zmonteca** [comment]
No worries. Thanks.

**Pull request merged**
